sonar.projectKey=laravel-app
sonar.projectName=Laravel App
sonar.sourceEncoding=UTF-8

sonar.sources=app
sonar.tests=tests

sonar.php.coverage.reportPaths=coverage.xml

sonar.exclusions=vendor/**,storage/**,bootstrap/**
